version: '3'

services:
  pgsql:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  adminer:
    image: adminer
    ports:
      - "9180:8080"
    volumes:
    - ./db.sqlite3:/tmp/db.sqlite3:delegated
    - ./docker/login.php:/var/www/html/plugins-enabled/login.php:delegated

  web:
    image: hillliu/django-slim:app
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    volumes:
    - .:/app:delegated
    ports:
      - "${WEB_PORT-8000}:8000"

  worker:
    image: hillliu/django-slim:app
    command: celery -A main_app worker -l info 
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=main_app.settings
    volumes:
    - .:/app:delegated

  rabbitmq:
    image: rabbitmq:management-alpine 
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE=12345
      - RABBITMQ_DEFAULT_VHOST=/

